### ISSUE TITLE
Why show cpumun 1 on my quad core CPU Router?

### ISSUE THREAD

**Issue by snowrice** [trojan-gfw/openwrt-trojan#14] opened 2020-02-11 16:41 UTC
Starting Message:
multicore_ready is false
cpunum is 1

My router is Rpi2B (4 cores) ,but only support single thread?

**Comment by GreaterFire** [comment] 2020-02-11 16:46
Duplicate of #13

**Comment by wongsyrone** [comment] 2020-02-12 00:28
Post the output of `cat /proc/cpuinfo`

**Comment by wongsyrone** [comment] 2020-02-12 00:33
Make sure `reuse_port` is true

https://github.com/trojan-gfw/trojan/blob/v1.14.1/examples/client.json-example#L29

**Comment by snowrice** [comment] 2020-02-12 07:52
> Post the output of `cat /proc/cpuinfo`

processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 2
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 3
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : BCM2835
Revision        : 2a01041
Serial          : 00000000135336e7

**Comment by snowrice** [comment] 2020-02-12 07:59
> Make sure `reuse_port` is true
> 
> https://github.com/trojan-gfw/trojan/blob/v1.14.1/examples/client.json-example#L29

After I change  "reuse_port": true, I got the following output:

multicore_ready is true
/etc/rc.common: return: line 38: Illegal number:

**Comment by wongsyrone** [comment] 2020-02-13 02:38
OK, will fix it

**Comment by wongsyrone** [comment] 2020-02-23 03:21
Fixed via https://github.com/trojan-gfw/openwrt-trojan/commit/1022c33195855426022aa9db74bbfdd49d89dd37

**Closed as completed by wongsyrone** 2020-02-23 03:21 UTC

**Comment by snowrice** [comment] 2020-03-03 03:54
Thanks for taking workload to fix my issue.
The problem of my RPI2 was fixed.
